module.exports = {
    manufacturerId: new Map([
        [1, 'garmin'],
        [6, 'srm'],
        [7, 'quarq'],
        [13, 'dynastream_oem'],
        [23, 'suunto'],
        [32, 'wahoo_fitness'],
        [41, 'shimano'],
        [51, '4iiiis'],
        [63, 'specialized'],
        [67, 'bkool'],
        [69, 'stages_cycling'],
        [81, 'bontrager'],
        [86, 'elite'],
        [89, 'tacx'],
        [93, 'inside_ride_technologies'],
        [99, 'look'],
        [100, 'campagnolo_srl'],
        [102, 'praxisworks'],
        [108, 'giant_manufacturing_co'],
        [112, 'bryton_sensors'],
        [121, 'kinetic'],
        [123, 'polar_electro'],
        [128, 'ifit_com'],
        [132, 'cycplus'],
        [144, 'zwift_byte'],
        [258, 'lezyne'],
        [260, 'zwift'],
        [263, 'favero_electronics'],
        [265, 'strava'],
        [267, 'bryton'],
        [268, 'sram'],
        [279, 'cycliq'],
        [281, 'trainer_road'],
        [282, 'the_sufferfest'],
        [283, 'fullspeedahead'],
        [289, 'hammerhead'],
        [305, 'whoop'],
        [311, 'syncros'],
        [313, 'cannondale']
    ]),
    antTopics: new Map([
    // === CommonSensor
        // ['DeviceID', {'name': 'device_id', 'cache': false}],  
        ['ManId', {'name': 'manufacturer', 'cache': false}],
        // ['HwVersion', {'name': 'hardware_version', 'cache': false}],
        // ['SwVersion', {'name': 'software_version', 'cache': false}],
        // ['ModelNum', {'name': 'model_number', 'cache': false}],
        // ['Motion', {'name': 'motion', 'cache': false}],
        ['BatteryLevel', {'name': 'battery_level', 'cache': true}],
        ['BatteryStatus', {'name': 'battery_status', 'cache': true}],
        // ['BatteryVoltage', {'name': 'battery_voltage', 'cache': false}],
        // ['OperatingTime', {'name': 'operating_time', 'cache': false}],
        // ['SerialNumber', {'name': 'serial_number', 'cache': false}],
        // ['Rssi', {'name': 'rssi', 'cache': false}],
        // ['Threshold', {'name': 'threshold', 'cache': false}],
    // === HeartrateSensor
        // ['BeatTime', {'name': 'beat_time', 'cache': false}],
        // ['BeatCount', {'name': 'beat_count', 'cache': false}],
        ['ComputedHeartRate', {'name': 'computed_heartrate', 'cache': true}],
        // ['PreviousBeat', {'name': 'previous_beat', 'cache': false}],
        // ['IntervalAverage', {'name': 'interval_average', 'cache': false}],
        // ['IntervalMax', {'name': 'interval_max', 'cache': false}],
        // ['SessionAverage', {'name': 'session_average', 'cache': false}],
        // ['SupportedFeatures', {'name': 'supported_features', 'cache': false}],
        // ['EnabledFeatures', {'name': 'enabled_features', 'cache': false}],
    // === BicyclePowerSensor
        // ['PedalPower', {'name': 'pedal_power', 'cache': false}],
        // ['RightPedalPower', {'name': 'pedal_power_right', 'cache': false}],
        // ['LeftPedalPower', {'name': 'pedal_power_left', 'cache': false}],
        ['Cadence', {'name': 'calculated_cadence', 'cache': true}],
        // ['AccumulatedPower', {'name': 'accumulated_power', 'cache': false}],
        ['Power', {'name': 'power', 'cache': true}],
        // ['offset', {'name': 'offset', 'cache': false}],
        // ['EventCount', {'name': 'event_count', 'cache': false}],
        // ['TimeStamp', {'name': 'timestamp', 'cache': false}],
        // ['Slope', {'name': 'slope', 'cache': false}],
        // ['TorqueTicksStamp', {'name': 'torque_ticks_stamp', 'cache': false}],
        // ['CalculatedTorque', {'name': 'calculated_torque', 'cache': false}],
        // ['CalculatedPower', {'name': 'calculated_power', 'cache': false}],
    // === CadenceSensor
        // ['CadenceEventTime', {'name': 'cadence_event_time', 'cache': false}],
        // ['CumulativeCadenceRevolutionCount', {'name': 'cumulative_cadence_revolution_count', 'cache': false}],
        ['CalculatedCadence', {'name': 'calculated_cadence', 'cache': true}],
    // === SpeedSensor
        // ['SpeedEventTime', {'name': 'speed_event_time', 'cache': false}],
        // ['CumulativeSpeedRevolutionCount', {'name': 'cumulative_speed_revolution_count', 'cache': false}],
        ['CalculatedDistance', {'name': 'calculated_distance', 'cache': true}],
        ['CalculatedSpeed', {'name': 'calculated_speed', 'cache': true}],
    // === FitnessEquipment
        // ['Temperature', {'name': 'temperature', 'cache': false}],
        // ['ZeroOffset', {'name': 'zero_offset', 'cache': false}],
        // ['SpinDownTime', {'name': 'spindown_time', 'cache': false}],
        ['EquipmentType', {'name': 'equipment_type', 'cache': false}],
        // ['ElapsedTime', {'name': 'elapsed_time', 'cache': false}],
        ['Distance', {'name': 'calculated_distance', 'cache': true}],
        // ['RealSpeed', {'name': 'real_speed', 'cache': false}],
        ['VirtualSpeed', {'name': 'calculated_speed', 'cache': true}],
        ['HeartRate', {'name': 'computed_heartrate', 'cache': true}],
        // ['HeartRateSource', {'name': 'heartrate_souce', 'cache': false}],
        // ['State', {'name': 'state', 'cache': false}],
        // ['CycleLength', {'name': 'cycle_length', 'cache': false}],
        // ['Incline', {'name': 'incline', 'cache': false}],
        // ['Resistance', {'name': 'resistance', 'cache': false}],
        // ['METs', {'name': 'mets', 'cache': false}],
        // ['CaloricBurnRate', {'name': 'caloric_burn_rate', 'cache': false}],
        // ['Calories', {'name': 'calories', 'cache': false}],
        // ['_EventCount0x19', {'name': 'event_count', 'cache': false}],
        ['InstantaneousPower', {'name': 'instantaneous_power', 'cache': true}],
        ['AveragePower', {'name': 'average_power', 'cache': true}],
        // ['TrainerStatus', {'name': 'trainer_status', 'cache': false}],
        // ['TargetStatus', {'name': 'target_status', 'cache': false}],
        // ['PairedDevices', {'name': 'paired_devices', 'cache': false}],
    ]),
};